CREATE TABLE FUNCIONARIO (
  ID_FUNC INT,
  NOME VARCHAR(40),
  CPF CHAR(14),
  SENHA VARCHAR(20),
  PRIMARY KEY (ID_FUNC)
);

CREATE TABLE CLIENTE (
  CPF CHAR(14) NOT NULL,
  NOME VARCHAR(40),
  PRIMARY KEY (CPF)
);

CREATE TABLE FORNECEDOR (
  CNPJ CHAR(18) NOT NULL,
  NOME VARCHAR(40),
  PRIMARY KEY (CNPJ)
);

CREATE TABLE PRODUTO (
  CODPROD INT,
  NOMEPROD VARCHAR(50),
  QTDPROD INT,
  DESCRPROD VARCHAR(200),
  FK_FORNCNPJ CHAR(18),
  PRIMARY KEY (CODPROD),
  FOREIGN KEY (FK_FORNCNPJ) REFERENCES FORNECEDOR(CNPJ)
);

select * from funcionario;
select * from cliente;
select * from fornecedor;
select * from produto;


CREATE OR REPLACE PROCEDURE p_addFuncionario (ID_FUNC IN INT, NOME IN VARCHAR, CPF IN CHAR, SENHA IN VARCHAR) AS
BEGIN
  INSERT INTO FUNCIONARIO VALUES (ID_FUNC, NOME, CPF, SENHA);
END p_addFuncionario;
/

