-- drop database sicone;

select * from funcionario;
select * from cliente;
select * from fornecedor;
select * from produto;

CREATE TABLE FUNCIONARIO (
  ID INT NOT NULL,
  NOME VARCHAR(40),
  CPF CHAR(14),
  SENHA VARCHAR(20),
  PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE (
  CPF CHAR(14) NOT NULL,
  NOME VARCHAR(40),
  PRIMARY KEY (CPF)
);

CREATE TABLE FORNECEDOR (
  CNPJ CHAR(18) NOT NULL,
  NOME VARCHAR(40),
  PRIMARY KEY (CNPJ)
);

CREATE TABLE PRODUTO (
  CODPROD INT,
  NOMEPROD VARCHAR(50),
  QTDPROD INT,
  DESCRPROD VARCHAR(200),
  FK_FORNCNPJ CHAR(18),
  PRIMARY KEY (CODPROD),
  FOREIGN KEY (FK_FORNCNPJ) REFERENCES FORNECEDOR(CNPJ)
);