create database sicone;
use sicone;

-- drop database sicone;

select * from funcionario;
select * from cliente;
select * from fornecedor;
select * from produto;
select * from pedido;

CREATE TABLE FUNCIONARIO (
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(40),
  CPF CHAR(14),
  SENHA VARCHAR(20),
  PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE (
  CPF CHAR(14) NOT NULL,
  NOME VARCHAR(40),
  PRIMARY KEY (CPF)
);

CREATE TABLE FORNECEDOR (
  CNPJ CHAR(18) NOT NULL,
  NOME VARCHAR(40),
  PRIMARY KEY (CNPJ)
);

CREATE TABLE PRODUTO (
  CODPROD INT AUTO_INCREMENT,
  NOMEPROD VARCHAR(50),
  QTDPROD INT,
  DESCRPROD VARCHAR(200),
  FK_FORNCNPJ CHAR(18),
  PRIMARY KEY (CODPROD),
  FOREIGN KEY (FK_FORNCNPJ) REFERENCES FORNECEDOR(CNPJ)
);

CREATE TABLE PEDIDO (
  NUMPEDIDO INT,
  DATAPEDIDO DATE,
  FK_CPF CHAR(14),
  PRIMARY KEY (NUMPEDIDO),
  FOREIGN KEY (FK_CPF) REFERENCES CLIENTE(CPF)
);

CREATE TABLE ITEMPEDIDO (
  FK_CODPROD INT,
  FK_NOMEPROD VARCHAR(50),
  FK_QTDPROD INT,
  FK_NUMPEDIDO INT
 -- PRIMARY KEY (FK_CODPROD, FK_NUMPEDIDO)
);

DROP TABLE PRODUTO;
DROP TABLE ITEMPEDIDO;

ALTER TABLE ITEMPEDIDO ADD CONSTRAINT NUMPEDIDO_FK_NUMPEDIDO FOREIGN KEY (FK_NUMPEDIDO) REFERENCES PEDIDO(NUMPEDIDO);
ALTER TABLE ITEMPEDIDO ADD CONSTRAINT CODPROD_FK_CODPROD FOREIGN KEY (FK_CODPROD) REFERENCES PRODUTO(CODPROD);

ALTER TABLE ITEMPEDIDO ADD CONSTRAINT NOMEPROD_FK_NOMEPROD FOREIGN KEY (FK_NOMEPROD) REFERENCES PRODUTO(NOMEPROD);
ALTER TABLE ITEMPEDIDO ADD CONSTRAINT QTDPROD_FK_QTDPROD FOREIGN KEY (FK_QTDPROD) REFERENCES PRODUTO(QTDPROD);