create database sicone;
use sicone;

-- drop database sicone;

select * from funcionario;
select * from cliente;
select * from fornecedor;
select * from produto;

CREATE TABLE FUNCIONARIO (
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(40),
  CPF CHAR(14),
  SENHA VARCHAR(20),
  PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE (
  CPF CHAR(14) NOT NULL,
  NOME VARCHAR(40),
  PRIMARY KEY (CPF)
);

CREATE TABLE FORNECEDOR (
  CNPJ CHAR(18) NOT NULL,
  NOME VARCHAR(40),
  PRIMARY KEY (CNPJ)
);

CREATE TABLE PRODUTO (
  CODPROD INT AUTO_INCREMENT,
  NOMEPROD VARCHAR(50),
  QTDPROD INT,
  DESCRPROD VARCHAR(200),
  FK_FORNCNPJ CHAR(18),
  PRIMARY KEY (CODPROD)
);



CREATE TABLE PEDIDO (
  NUMPEDIDO INT,
  DATAPEDIDO DATE,
  PRIMARY KEY (NUMPEDIDO)
);

CREATE TABLE ITEMPEDIDO (
  CODPROD INT,
  NOMEPROD VARCHAR(20),
  QTDPROD INT,
  PRIMARY KEY (CODPROD)
);

-- ALTER TABLE PRODUTO ADD CONSTRAINT CNPJ_FK_FORN FOREIGN KEY FK_FORNCNPJ REFERENCES FORNECEDOR(CNPJ);